name: Publish helper
run-name: Product information formatting
on: workflow_dispatch

jobs:
  format-products:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Create credentials.json
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json
      - run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client python-telegram-bot requests
          python publish/publishProducts.py