name: Scraping workflow
on:
  schedule:
    - cron: '30  10  *  *  *'

  workflow_dispatch:
    inputs:

      # fetch parameters, default is defined in fetch/fetch_variables.py
      searchTerm:
        description: 'search_term'
        required: false
        type: string

      minPriceSEK:
        description: 'min_price_sek'
        required: false
        type: string

      maxPriceSEK:
        description: 'max_price_sek'
        required: false
        type: string

      minPriceUSD:
        description: 'min_price_usd'
        required: false
        type: string

      maxPriceUSD:
        description: 'max_price_usd'
        required: false
        type: string

      # optional option of choosing which marketplaces to fetch from, default is all
      fetchBlocket:
        description: 'Fetch Blocket'
        required: false
        type: boolean
        default: true
      
      fetchEbay:
        description: 'Fetch Ebay (USD)'
        required: false
        type: boolean
        default: true
      
      fetchFacebook:
        description: 'Fetch Facebook'
        required: false
        type: boolean
        default: true
      
      fetchTradera:
        description: 'Fetch Tradera'
        required: false
        type: boolean
        default: true
      
      fetchVinted:
        description: 'Fetch Vinted'
        required: false
        type: boolean
        default: true

jobs:
  fetch-tradera:
    if: github.event_name == 'schedule' || inputs.fetchTradera != false
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SEARCH_TERM: ${{ inputs.searchTerm || '' }}
        MIN_PRICE_SEK: ${{ inputs.minPriceSEK || '' }}
        MAX_PRICE_SEK: ${{ inputs.maxPriceSEK || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install tradera_api
        run: pip install tradera_api python-dotenv requests supabase
      
      - name: Run tradera_marketplace.py
        run: python fetch/tradera/tradera_marketplace.py

  fetch-facebook:
    if: github.event_name == 'schedule' || inputs.fetchFacebook != false
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        SEARCH_TERM: ${{ inputs.searchTerm || '' }}
        MIN_PRICE_SEK: ${{ inputs.minPriceSEK || '' }}
        MAX_PRICE_SEK: ${{ inputs.maxPriceSEK || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run fb_marketplace.py
        run: python fetch/facebook/fb_marketplace.py

  fetch-blocket:
    if: github.event_name == 'schedule' || inputs.fetchBlocket != false
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SEARCH_TERM: ${{ inputs.searchTerm || '' }}
        MIN_PRICE_SEK: ${{ inputs.minPriceSEK || '' }}
        MAX_PRICE_SEK: ${{ inputs.maxPriceSEK || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run blocket_marketplace.py
        run: python fetch/blocket/blocket_marketplace.py

  fetch-ebay:
    if: github.event_name == 'schedule' || inputs.fetchEbay != false
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
        EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
        SEARCH_TERM: ${{ inputs.searchTerm || '' }}
        MIN_PRICE_USD: ${{ inputs.minPriceUSD || '' }}
        MAX_PRICE_USD: ${{ inputs.maxPriceUSD || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run ebay_marketplace.py
        run: python fetch/ebay/ebay_marketplace.py

  fetch-vinted:
    if: github.event_name == 'schedule' || inputs.fetchVinted != false
    runs-on: ubuntu-latest
    environment: telegramApi
    env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CHAT_ID: ${{ secrets.BOT_CHAT_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SUPABASE_EMAIL: ${{ secrets.SUPABASE_EMAIL }}
        SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        SEARCH_TERM: ${{ inputs.searchTerm || '' }}
        MIN_PRICE_SEK: ${{ inputs.minPriceSEK || '' }}
        MAX_PRICE_SEK: ${{ inputs.maxPriceSEK || '' }}
        MIN_PRICE_USD: ${{ inputs.minPriceUSD || '' }}
        MAX_PRICE_USD: ${{ inputs.maxPriceUSD || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run vinted_marketplace.py
        run: python fetch/vinted/vinted_marketplace.py
